version: 2
jobs:
  checkout_code:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/microauth-vkontakte
    steps:
      - checkout
      - attach_workspace:
          at: ~/microauth-vkontakte
      - restore_cache:
          keys:
            - 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
            - 'yarn-cache-{{ .Branch }}'
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: 'yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}'
          paths: node_modules
      - persist_to_workspace:
          root: .
          paths: .
  check_dependencies:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/microauth-vkontakte
    steps:
      - checkout
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn start validate.dependencies
  validate_code:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/microauth-vkontakte
    steps:
      - checkout
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn start validate
  test_node_6:
    docker:
      - image: 'circleci/node:6'
    working_directory: ~/microauth-vkontakte
    steps:
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn test
  test_node_7:
    docker:
      - image: 'circleci/node:7'
    working_directory: ~/microauth-vkontakte
    steps:
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn test
  test_node_8:
    docker:
      - image: 'circleci/node:8'
    working_directory: ~/microauth-vkontakte
    steps:
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn test
  test_latest_and_report:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/microauth-vkontakte
    steps:
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn start test.coverage
      - run: yarn start reportCoverage
      - store_artifacts:
          path: ./coverage/clover.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: ./coverage/clover.xml
  release:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/microauth-vkontakte
    steps:
      - attach_workspace:
          at: ~/microauth-vkontakte
      - run: yarn start release || true
workflows:
  version: 2
  test_and_release:
    jobs:
      - checkout_code
      - check_dependencies:
          requires:
            - checkout_code
      - validate_code:
          requires:
            - checkout_code
      - test_node_6:
          requires:
            - checkout_code
            - check_dependencies
            - validate_code
      - test_node_7:
          requires:
            - checkout_code
            - check_dependencies
            - validate_code
      - test_node_8:
          requires:
            - checkout_code
            - check_dependencies
            - validate_code
      - test_latest_and_report:
          requires:
            - checkout_code
            - check_dependencies
            - validate_code
      - release:
          requires:
            - test_node_6
            - test_node_7
            - test_node_8
            - test_latest_and_report
          filters:
            branches:
              only: master
